name: tfsec checksums
on:
  release:
    types: [published]

jobs:
  build:
    name: adding release checks sums
    runs-on: ubuntu-latest

    steps:
    - name: Update release hashes
      uses: MCJack123/ghaction-generate-release-hashes@v1
      with:
        hash-type: sha256
        file-name: checksums.txt
    
    - name: Upload checksums file
      uses: actions/upload-artifact@v2
      with:
        name: Asset Checksums
        path: checksums.txt
